version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - sudo yum update -y
      - sudo yum install node.js -y
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm pack
  post_build:
    commands:
      - ls -l
  artifacts:
    files:
      - '*.tgz'